---
title: "Lab 00 - Hello IDS!"
author: "Ethan Longhurst"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Ethan", "Adam", 
           "Sacari", "Donald","Alex"),
  github_username = c("EthanLonghurst", "adamrobbins-hub", "sacari-culu", 
                      "donaldmac08", "alex19hill-ai"), 
  colour = c("blue", "yellow", "green", 
             "blue", "blue"),
  hobby = c("football", "music", "basketball", 
            "rugby", "tennis"),
  favourite_number = c(5, 9, 9, 9, 7)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

shows us the colour number and the usernames of everyone in the group

